In [1]:
import pandas as pd
import geopandas as gpd
import bqplot
import numpy as np
import traitlets
import ipywidgets
import matplotlib.pyplot as plt
# I usually import as much as possible, but not always use all of them

In [2]:
temp  = pd.read_csv('https://query.data.world/s/sk7daquhia6dyfmtcga7rwa4sas7ev')
temp.head()

,last_update,location_type,state,county_name,county_name_long,fips_code,lat,lon,NCHS_urbanization,total_population,confirmed,confirmed_per_100000,deaths,deaths_per_100000
0,2021-05-01 12:20:41 UTC,county,Alabama,Autauga,"Autauga, Alabama, US",1001.0,32.539527,-86.644082,Medium metro,55200.0,6904,12507.25,107,193.84
1,2021-05-01 12:20:41 UTC,county,Alabama,Baldwin,"Baldwin, Alabama, US",1003.0,30.727750,-87.722071,Small metro,208107.0,20941,10062.61,305,146.56
2,2021-05-01 12:20:41 UTC,county,Alabama,Barbour,"Barbour, Alabama, US",1005.0,31.868263,-85.387129,Non-core,25782.0,2300,8920.95,56,217.21
3,2021-05-01 12:20:41 UTC,county,Alabama,Bibb,"Bibb, Alabama, US",1007.0,32.996421,-87.125115,Large fringe metro,22527.0,2594,11515.07,63,279.66
4,2021-05-01 12:20:41 UTC,county,Alabama,Blount,"Blount, Alabama, US",1009.0,33.982109,-86.567906,Large fringe metro,57645.0,6613,11471.94,135,234.19

### Introduction

I will be using the dataset I found from Data.world, which describes Covid-19 cases in United States distributed by the state and county names as well as their specific coordinates on latitude and longitude. There exist multiple elements in the dataset such as "total population", "confirmed cases" and "deaths", and the like to describe the overall severity and seriousness of Covid-19 pandemic across the nation. Throughout part 1 of the final project I suggested multiple variety of visualization and through this part 2 I will be elaborating on one of the examples and incorporating interactivity.

I had chosen the first example from part 1, which resembles practices done throughout Week 5 of the course and homework 6, because I found it more applicable in this case and my capability. Furthermore, I found this dataset very fitting to the current trend and interest of the world. There were some even arguing that the pandemic is not real, so I came to use this dataset to reflect on the severity of this pandemic and its impact on all of us.

The dataset was obtained via Data.world as aforementioned, and further detail had been provided during part 1 of the final project. The sources for the dataset and download are provided in this notebook, although anyone hoping to use this notebook does not need to download supplimentary files.


Source: https://data.world/associatedpress/johns-hopkins-coronavirus-case-tracker

csv download link: https://query.data.world/s/sk7daquhia6dyfmtcga7rwa4sas7ev

#### Code

(Testing phase)

In [3]:
temp.loc[temp['fips_code'] > 80000]

,last_update,location_type,state,county_name,county_name_long,fips_code,lat,lon,NCHS_urbanization,total_population,confirmed,confirmed_per_100000,deaths,deaths_per_100000
3198,2020-12-21 13:27:30 UTC,out_of_state,Alabama,Out of AL,"Out of AL, Alabama, US",80001.0,NaN,NaN,NaN,NaN,0,NaN,0,NaN
3199,2021-05-01 12:20:41 UTC,out_of_state,Arizona,Out of AZ,"Out of AZ, Arizona, US",80004.0,NaN,NaN,NaN,NaN,0,NaN,0,NaN
3200,2021-05-01 12:20:41 UTC,out_of_state,Colorado,Out of CO,"Out of CO, Colorado, US",80008.0,NaN,NaN,NaN,NaN,0,NaN,0,NaN
3201,2021-05-01 12:20:41 UTC,out_of_state,Georgia,Out of GA,"Out of GA, Georgia, US",80013.0,NaN,NaN,NaN,NaN,29201,NaN,626,NaN
3202,2021-05-01 12:20:41 UTC,out_of_state,Hawaii,Out of HI,"Out of HI, Hawaii, US",80015.0,NaN,NaN,NaN,NaN,1084,NaN,3,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3256,2020-12-21 13:27:30 UTC,count_unassigned_to_location,Virginia,Unassigned,"Unassigned, Virginia, US",90051.0,NaN,NaN,NaN,NaN,0,NaN,0,NaN
3257,2021-05-01 12:20:41 UTC,count_unassigned_to_location,Washington,Unassigned,"Unassigned, Washington, US",90053.0,NaN,NaN,NaN,NaN,1491,NaN,3,NaN
3258,2021-05-01 12:20:41 UTC,count_unassigned_to_location,West Virginia,Unassigned,"Unassigned, West Virginia, US",90054.0,NaN,NaN,NaN,NaN,0,NaN,0,NaN
3259,2021-05-01 12:20:41 UTC,count_unassigned_to_location,Wisconsin,Unassigned,"Unassigned, Wisconsin, US",90055.0,NaN,NaN,NaN,NaN,0,NaN,0,NaN
3260,2021-05-01 12:20:41 UTC,count_unassigned_to_location,Wyoming,Unassigned,"Unassigned, Wyoming, US",90056.0,NaN,NaN,NaN,NaN,0,NaN,0,NaN

In [4]:
temp1 = temp[temp['fips_code'] < 80000]
temp2 = temp1.fillna(1)
temp2.head()

,last_update,location_type,state,county_name,county_name_long,fips_code,lat,lon,NCHS_urbanization,total_population,confirmed,confirmed_per_100000,deaths,deaths_per_100000
0,2021-05-01 12:20:41 UTC,county,Alabama,Autauga,"Autauga, Alabama, US",1001.0,32.539527,-86.644082,Medium metro,55200.0,6904,12507.25,107,193.84
1,2021-05-01 12:20:41 UTC,county,Alabama,Baldwin,"Baldwin, Alabama, US",1003.0,30.727750,-87.722071,Small metro,208107.0,20941,10062.61,305,146.56
2,2021-05-01 12:20:41 UTC,county,Alabama,Barbour,"Barbour, Alabama, US",1005.0,31.868263,-85.387129,Non-core,25782.0,2300,8920.95,56,217.21
3,2021-05-01 12:20:41 UTC,county,Alabama,Bibb,"Bibb, Alabama, US",1007.0,32.996421,-87.125115,Large fringe metro,22527.0,2594,11515.07,63,279.66
4,2021-05-01 12:20:41 UTC,county,Alabama,Blount,"Blount, Alabama, US",1009.0,33.982109,-86.567906,Large fringe metro,57645.0,6613,11471.94,135,234.19

In [5]:
temp3 = temp2.fillna(0)

i = pd.pivot_table(temp3, 
                   index=["state"],
                   values=["confirmed_per_100000"],
                   columns=["NCHS_urbanization"],
                   aggfunc=np.sum)

np.log10(i.values)

array([[       nan, 4.06207144, 4.81795058, 4.93780686, 5.02694212,
        5.46153408, 5.19769061],
       [0.30103   ,        nan,        nan, 4.32629263, 3.87262238,
        5.21694124, 3.88477328],
       [       nan, 4.1012706 , 4.08729221, 4.05271818, 4.77397248,
        4.52771959, 4.77250258],
       [       nan,        nan, 4.08935748, 5.05754972, 5.2737669 ,
        5.61313267, 5.01402851],
       [       nan, 4.80651473, 4.76608232, 5.08052771, 4.75472482,
        4.90882224, 4.89346542],
       [       nan, 4.00684968, 4.7995021 , 4.61397864, 5.07090935,
        5.52362356, 4.30887802],
       [       nan, 3.96031758, 4.1418024 , 4.58059999, 3.89350932,
               nan,        nan],
       [       nan,        nan, 4.04551504, 4.05928314,        nan,
               nan, 3.99740386],
       [       nan, 3.84311874,        nan,        nan,        nan,
               nan,        nan],
       [       nan, 4.75341781, 5.03387748, 5.25431758, 4.87116542,
        5.26668218, 4.92457631],
       [       nan, 3.97357624, 5.47296951, 5.23091538, 5.49585474,
        5.75968531, 5.45264598],
       [       nan,        nan,        nan, 3.41131155, 3.23893136,
               nan, 3.41635588],
       [       nan,        nan,        nan, 4.68557784, 5.19530191,
        5.15025962, 4.85413551],
       [       nan, 4.00993719, 5.24328823, 5.03672225, 5.41774295,
        5.63087111, 5.11438244],
       [       nan, 4.01727464, 5.34925891, 4.90890913, 5.44173607,
        5.35151601, 5.16694537],
       [       nan,        nan,        nan, 5.13964498, 5.30310195,
        5.83717844, 5.04342673],
       [       nan,        nan, 4.6799687 , 4.71639762, 5.34606503,
        5.87081764, 4.92255077],
       [       nan, 4.01494329, 5.06510008, 5.00818015, 5.39949722,
        5.76865195, 4.98417623],
       [       nan, 3.88467927, 4.83294644, 5.26755672, 4.92161568,
        5.34824768, 4.95014678],
       [       nan,        nan,        nan, 4.1861163 , 3.67113765,
        4.48739576, 4.01167234],
       [       nan, 3.91831033, 4.90143947, 4.52481593, 4.14404277,
        4.30780379, 4.16727331],
       [       nan, 4.05982838, 4.69128356, 4.40654648, 3.54042709,
               nan, 4.0519925 ],
       [       nan, 4.28726861, 4.88834082, 4.8464213 , 5.31304149,
        5.37712129, 4.87810741],
       [       nan, 4.27532886, 5.11270033, 4.25820756, 5.29275764,
        5.65191855, 5.06302196],
       [       nan,        nan, 4.76426948, 4.93153948, 5.45655221,
        5.64087809, 4.48671222],
       [       nan, 4.11937864, 5.08507016, 4.7581212 , 5.34279635,
        5.73075997, 5.10776731],
       [       nan,        nan,        nan,        nan, 4.75335735,
        5.64178491, 4.65564584],
       [       nan,        nan,        nan, 4.89465727, 5.20483373,
        5.75565274, 4.8505212 ],
       [       nan, 4.05655346,        nan, 4.10218115, 4.66099669,
        4.66405603, 4.07173955],
       [       nan,        nan, 4.17561211, 3.92724611, 4.49299939,
        3.68625811,        nan],
       [       nan, 4.57281121, 5.13493764, 4.47170043,        nan,
               nan, 4.3062753 ],
       [       nan,        nan,        nan, 4.4795255 , 5.12038178,
        4.86251718, 4.47115465],
       [       nan, 4.88196415, 5.10183787, 4.85795219, 4.97544311,
        4.83380704, 4.7136649 ],
       [       nan, 4.270383  , 5.00631956, 5.34667382, 5.42657917,
        5.39350905, 4.94322772],
       [       nan,        nan,        nan,        nan, 4.98037929,
        5.69359971, 4.93310734],
       [       nan, 4.45184337, 5.2027923 , 5.06461536, 5.47379326,
        5.15964674, 4.67322418],
       [       nan, 4.04141479, 4.8227675 , 4.97462663, 5.35210345,
        5.67884192, 4.35473694],
       [       nan, 3.66259541, 4.19345771, 4.14854466, 4.85737743,
        4.65411577, 4.3015619 ],
       [       nan, 4.23737557, 4.97013372, 5.10375198, 5.16770162,
        5.07005816, 4.98725845],
       [5.41143124,        nan,        nan,        nan,        nan,
               nan,        nan],
       [       nan, 4.17817175, 4.56763536,        nan,        nan,
               nan,        nan],
       [       nan,        nan, 4.56156728, 5.30858787, 4.96136148,
        5.11774081, 4.71826355],
       [       nan,        nan,        nan,        nan, 5.24180198,
        5.77605258, 5.03312797],
       [       nan, 4.36390423, 5.32796734, 5.22382158, 5.41602052,
        5.64262079, 5.09234755],
       [       nan, 4.78124785, 5.4733286 , 5.42399395, 5.703575  ,
        6.10177442, 5.34503822],
       [       nan, 4.12058183, 4.04282271, 4.43418617, 4.45724224,
        4.09092926,        nan],
       [       nan,        nan,        nan,        nan, 4.32781629,
        4.22195983, 4.05798695],
       [       nan, 4.56069673, 5.50907722, 5.06646137, 4.84447308,
        5.59404168, 5.19345434],
       [       nan, 3.67299324, 4.2483463 , 4.66786734, 4.72676591,
        4.50971544, 4.77956128],
       [       nan,        nan, 3.90431352, 4.62915343, 4.79426471,
        5.30426544, 5.10619848],
       [       nan, 4.08030209, 4.83196232, 4.94406007, 5.21855562,
        5.52486623, 5.12631184],
       [       nan,        nan,        nan,        nan, 4.90818826,
        5.06463605, 4.28154353]])

In [6]:
covidus = pd.pivot_table(temp2, 
                                 index=["state"],
                                 values=["confirmed_per_100000"],
                                 columns=["NCHS_urbanization"],
                                  aggfunc=np.sum)
covidus

                     confirmed_per_100000                      \
NCHS_urbanization                       1 Large central metro
state
Alabama                               NaN            11536.43
Alaska                               2.00                 NaN
Arizona                               NaN            12626.14
Arkansas                              NaN                 NaN
California                            NaN            64049.35
Colorado                              NaN            10158.97
Connecticut                           NaN             9126.78
Delaware                              NaN                 NaN
District of Columbia                  NaN             6968.17
Florida                               NaN            56678.43
Georgia                               NaN             9409.71
Hawaii                                NaN                 NaN
Idaho                                 NaN                 NaN
Illinois                              NaN            10231.45
Indiana                               NaN            10405.78
Iowa                                  NaN                 NaN
Kansas                                NaN                 NaN
Kentucky                              NaN            10350.07
Louisiana                             NaN             7667.95
Maine                                 NaN                 NaN
Maryland                              NaN             8285.34
Massachusetts                         NaN            11477.00
Michigan                              NaN            19376.20
Minnesota                             NaN            18850.76
Mississippi                           NaN                 NaN
Missouri                              NaN            13163.72
Montana                               NaN                 NaN
Nebraska                              NaN                 NaN
Nevada                                NaN            11390.78
New Hampshire                         NaN                 NaN
New Jersey                            NaN            37394.80
New Mexico                            NaN                 NaN
New York                              NaN            76201.61
North Carolina                        NaN            18637.30
North Dakota                          NaN                 NaN
Ohio                                  NaN            28303.71
Oklahoma                              NaN            11000.56
Oregon                                NaN             4598.28
Pennsylvania                          NaN            17273.31
Puerto Rico                     257888.06                 NaN
Rhode Island                          NaN            15072.03
South Carolina                        NaN                 NaN
South Dakota                          NaN                 NaN
Tennessee                             NaN            23115.55
Texas                                 NaN            60429.34
Utah                                  NaN            13200.24
Vermont                               NaN                 NaN
Virginia                              NaN            36366.10
Washington                            NaN             4709.70
West Virginia                         NaN                 NaN
Wisconsin                             NaN            12031.01
Wyoming                               NaN                 NaN

                                                                               \
NCHS_urbanization    Large fringe metro Medium metro Micropolitan    Non-core
state
Alabama                        65758.30     86657.64    106400.12   289423.69
Alaska                              NaN     21197.89      7458.00   164793.94
Arizona                        12226.22     11290.63     59425.45    33706.96
Arkansas                       12284.50    114169.40    187830.84   410329.43
California                     58355.57    120372.62     56849.26    81062.92
Colorado                       63023.44     41112.95    117736.02   333905.49
Connecticut                    13861.25     38071.50      7825.45         NaN
Delaware                       11104.91     11462.60          NaN         NaN
District of Columbia                NaN          NaN          NaN         NaN
Florida                       108112.89    179604.65     74330.22   184791.58
Georgia                       297145.74    170182.69    313223.79   575023.12
Hawaii                              NaN      2578.17      1733.53         NaN
Idaho                               NaN     48481.70    156784.06   141338.22
Illinois                      175100.84    108823.39    261663.38   427436.01
Indiana                       223490.42     81079.14    276526.06   224654.96
Iowa                                NaN    137925.63    200956.45   687350.80
Kansas                         47859.56     52047.23    221852.86   742707.21
Kentucky                      116171.63    101901.40    250898.01   587018.72
Louisiana                      68068.54    185164.07     83486.39   222970.64
Maine                               NaN     15350.28      4689.62    30718.20
Maryland                       79696.54     33482.35     13932.94    20314.39
Massachusetts                  49122.85     25500.37      3470.78         NaN
Michigan                       77328.72     70213.61    205608.70   238298.49
Minnesota                     129628.45     18122.06    196226.49   448661.24
Mississippi                    58112.49     85416.05    286122.63   437399.31
Missouri                      121638.25     57295.59    220189.37   537972.37
Montana                             NaN          NaN     56670.54   438313.56
Nebraska                            NaN     78461.62    160263.17   569708.56
Nevada                              NaN     12652.64     45813.84    46137.71
New Hampshire                  14983.46      8457.58     31117.12     4855.77
New Jersey                    136438.72     29627.87          NaN         NaN
New Mexico                          NaN     30166.54    131941.61    72864.70
New York                      126426.43     72102.81     94502.46    68203.56
North Carolina                101465.77    222164.07    267041.75   247462.30
North Dakota                        NaN          NaN     95582.70   493855.29
Ohio                          159511.61    116042.04    297709.89   144426.45
Oklahoma                       66491.71     94324.96    224959.04   477355.49
Oregon                         15611.97     14078.12     72007.45    45093.69
Pennsylvania                   93354.17    126984.87    147130.13   117505.49
Puerto Rico                         NaN          NaN          NaN         NaN
Rhode Island                   36951.78          NaN          NaN         NaN
South Carolina                 36439.07    203510.99     91487.44   131141.70
South Dakota                        NaN          NaN    174502.63   597107.58
Tennessee                     212797.90    167425.49    260627.67   439157.99
Texas                         297391.53    265456.86    505329.91  1264079.60
Utah                           11036.28     27176.04     28657.76    12329.04
Vermont                             NaN          NaN     21272.39    16670.93
Virginia                      322906.82    116536.34     69899.34   392682.62
Washington                     17715.21     46544.39     53304.75    32338.17
West Virginia                   8022.57     42574.88     62267.97   201495.54
Wisconsin                      67914.47     87914.41    165407.66   334862.28
Wyoming                             NaN          NaN     80944.67   116047.57


NCHS_urbanization    Small metro
state
Alabama                157648.78
Alaska                   7669.61
Arizona                 59224.66
Arkansas               103282.92
California              78246.59
Colorado                20364.70
Connecticut                  NaN
Delaware                 9940.40
District of Columbia         NaN
Florida                 84057.47
Georgia                283560.66
Hawaii                   2608.29
Idaho                   71471.93
Illinois               130131.50
Indiana                146874.15
Iowa                   110516.40
Kansas                  83666.34
Kentucky                96422.02
Louisiana               89155.22
Maine                   10272.41
Maryland                14698.51
Massachusetts           11271.78
Michigan                75527.90
Minnesota              115617.07
Mississippi             30669.89
Missouri               128164.37
Montana                 45252.84
Nebraska                70879.59
Nevada                  11796.13
New Hampshire                NaN
New Jersey              20243.02
New Mexico              29590.66
New York                51720.76
North Carolina          87746.08
North Dakota            85724.97
Ohio                    47122.05
Oklahoma                22632.73
Oregon                  20024.51
Pennsylvania            97108.77
Puerto Rico                  NaN
Rhode Island                 NaN
South Carolina          52271.33
South Dakota           107926.47
Tennessee              123693.69
Texas                  221328.95
Utah                         NaN
Vermont                 11428.44
Virginia               156118.49
Washington              60195.12
West Virginia          127702.23
Wisconsin              133755.56
Wyoming                 19122.45

In [7]:
np.log10(covidus.values)

array([[       nan, 4.06207144, 4.81795058, 4.93780686, 5.02694212,
        5.46153408, 5.19769061],
       [0.30103   ,        nan,        nan, 4.32629263, 3.87262238,
        5.21694124, 3.88477328],
       [       nan, 4.1012706 , 4.08729221, 4.05271818, 4.77397248,
        4.52771959, 4.77250258],
       [       nan,        nan, 4.08935748, 5.05754972, 5.2737669 ,
        5.61313267, 5.01402851],
       [       nan, 4.80651473, 4.76608232, 5.08052771, 4.75472482,
        4.90882224, 4.89346542],
       [       nan, 4.00684968, 4.7995021 , 4.61397864, 5.07090935,
        5.52362356, 4.30887802],
       [       nan, 3.96031758, 4.1418024 , 4.58059999, 3.89350932,
               nan,        nan],
       [       nan,        nan, 4.04551504, 4.05928314,        nan,
               nan, 3.99740386],
       [       nan, 3.84311874,        nan,        nan,        nan,
               nan,        nan],
       [       nan, 4.75341781, 5.03387748, 5.25431758, 4.87116542,
        5.26668218, 4.92457631],
       [       nan, 3.97357624, 5.47296951, 5.23091538, 5.49585474,
        5.75968531, 5.45264598],
       [       nan,        nan,        nan, 3.41131155, 3.23893136,
               nan, 3.41635588],
       [       nan,        nan,        nan, 4.68557784, 5.19530191,
        5.15025962, 4.85413551],
       [       nan, 4.00993719, 5.24328823, 5.03672225, 5.41774295,
        5.63087111, 5.11438244],
       [       nan, 4.01727464, 5.34925891, 4.90890913, 5.44173607,
        5.35151601, 5.16694537],
       [       nan,        nan,        nan, 5.13964498, 5.30310195,
        5.83717844, 5.04342673],
       [       nan,        nan, 4.6799687 , 4.71639762, 5.34606503,
        5.87081764, 4.92255077],
       [       nan, 4.01494329, 5.06510008, 5.00818015, 5.39949722,
        5.76865195, 4.98417623],
       [       nan, 3.88467927, 4.83294644, 5.26755672, 4.92161568,
        5.34824768, 4.95014678],
       [       nan,        nan,        nan, 4.1861163 , 3.67113765,
        4.48739576, 4.01167234],
       [       nan, 3.91831033, 4.90143947, 4.52481593, 4.14404277,
        4.30780379, 4.16727331],
       [       nan, 4.05982838, 4.69128356, 4.40654648, 3.54042709,
               nan, 4.0519925 ],
       [       nan, 4.28726861, 4.88834082, 4.8464213 , 5.31304149,
        5.37712129, 4.87810741],
       [       nan, 4.27532886, 5.11270033, 4.25820756, 5.29275764,
        5.65191855, 5.06302196],
       [       nan,        nan, 4.76426948, 4.93153948, 5.45655221,
        5.64087809, 4.48671222],
       [       nan, 4.11937864, 5.08507016, 4.7581212 , 5.34279635,
        5.73075997, 5.10776731],
       [       nan,        nan,        nan,        nan, 4.75335735,
        5.64178491, 4.65564584],
       [       nan,        nan,        nan, 4.89465727, 5.20483373,
        5.75565274, 4.8505212 ],
       [       nan, 4.05655346,        nan, 4.10218115, 4.66099669,
        4.66405603, 4.07173955],
       [       nan,        nan, 4.17561211, 3.92724611, 4.49299939,
        3.68625811,        nan],
       [       nan, 4.57281121, 5.13493764, 4.47170043,        nan,
               nan, 4.3062753 ],
       [       nan,        nan,        nan, 4.4795255 , 5.12038178,
        4.86251718, 4.47115465],
       [       nan, 4.88196415, 5.10183787, 4.85795219, 4.97544311,
        4.83380704, 4.7136649 ],
       [       nan, 4.270383  , 5.00631956, 5.34667382, 5.42657917,
        5.39350905, 4.94322772],
       [       nan,        nan,        nan,        nan, 4.98037929,
        5.69359971, 4.93310734],
       [       nan, 4.45184337, 5.2027923 , 5.06461536, 5.47379326,
        5.15964674, 4.67322418],
       [       nan, 4.04141479, 4.8227675 , 4.97462663, 5.35210345,
        5.67884192, 4.35473694],
       [       nan, 3.66259541, 4.19345771, 4.14854466, 4.85737743,
        4.65411577, 4.3015619 ],
       [       nan, 4.23737557, 4.97013372, 5.10375198, 5.16770162,
        5.07005816, 4.98725845],
       [5.41143124,        nan,        nan,        nan,        nan,
               nan,        nan],
       [       nan, 4.17817175, 4.56763536,        nan,        nan,
               nan,        nan],
       [       nan,        nan, 4.56156728, 5.30858787, 4.96136148,
        5.11774081, 4.71826355],
       [       nan,        nan,        nan,        nan, 5.24180198,
        5.77605258, 5.03312797],
       [       nan, 4.36390423, 5.32796734, 5.22382158, 5.41602052,
        5.64262079, 5.09234755],
       [       nan, 4.78124785, 5.4733286 , 5.42399395, 5.703575  ,
        6.10177442, 5.34503822],
       [       nan, 4.12058183, 4.04282271, 4.43418617, 4.45724224,
        4.09092926,        nan],
       [       nan,        nan,        nan,        nan, 4.32781629,
        4.22195983, 4.05798695],
       [       nan, 4.56069673, 5.50907722, 5.06646137, 4.84447308,
        5.59404168, 5.19345434],
       [       nan, 3.67299324, 4.2483463 , 4.66786734, 4.72676591,
        4.50971544, 4.77956128],
       [       nan,        nan, 3.90431352, 4.62915343, 4.79426471,
        5.30426544, 5.10619848],
       [       nan, 4.08030209, 4.83196232, 4.94406007, 5.21855562,
        5.52486623, 5.12631184],
       [       nan,        nan,        nan,        nan, 4.90818826,
        5.06463605, 4.28154353]])

In [8]:
# 2. scales -- for this data it will be a color scale
col_sc = bqplot.ColorScale()

# 3. Axis -- color axis ... skip for now

# 4. Mark -- a color-scale like mark
heat_map = bqplot.GridHeatMap(color=covidus, scales={'color':col_sc})

# 5. Interactions .. skip for now

#figure
fig = bqplot.Figure(marks=[heat_map])
fig

Figure(fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, marks=[GridHeatMap(color=array([[       …

#### Code

In [9]:
#--Grid heat map----------------------------------------------------------------------------
col_sc = bqplot.ColorScale(scheme="RdPu")
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

c_ax = bqplot.ColorAxis(scale = col_sc, 
                        orientation = 'vertical', 
                        side = 'right')
x_ax = bqplot.Axis(scale = x_sc)
y_ax = bqplot.Axis(scale = y_sc, 
                   orientation = 'vertical')


heat_map = bqplot.GridHeatMap(color = np.log10(covidus),
                              row = covidus.index,
                              scales = {'color': col_sc,
                                        'row': y_sc,
                                        'column': x_sc},
                              interactions = {'click': 'select'},
                              anchor_style = {'fill':'blue'}, 
                              selected_style = {'opacity': 1.0},
                              unselected_style = {'opacity': 1.0})

#fig = bqplot.Figure(marks = [heat_map], axes = [c_ax, y_ax, x_ax])
#fig

In [10]:
#--Line graph----------------------------------------------------------------------------
x_sch = bqplot.OrdinalScale()
y_sch = bqplot.LinearScale()
x_axh = bqplot.Axis(scale=x_sch, label='County')
y_axh = bqplot.Axis(scale=y_sch, label='Deaths', orientation='vertical')

#--Mask----------------------------------------------------------------------------
i,j = 16,5

mask = (temp2['state'] == covidus.index[i]) & \
       (temp2['NCHS_urbanization'] == covidus.columns.levels[1][j])

covidmask = temp2[mask]

grouped = covidmask.groupby("county_name")["deaths"].sum()
county = grouped.index
deaths = grouped.values

lines = bqplot.Lines(x = county, y = deaths,
                    scales = {'x': x_sch, 'y': y_sch})

#hist = bqplot.Hist(sample=grouped[i,j], normalized=False, # counts in each bin
#                  scales={'sample':x_sch, 'count':y_sch}, bins=5)


#grouped
#fig_lines = bqplot.Figure(marks = [lines], axes = [x_axh, y_axh])
#fig_lines

In [11]:
#--On select function----------------------------------------------------------------------------
def on_selected(change):
    i,j = change['owner'].selected[0]
    mask = (temp2['state'] == covidus.index[i]) & \
           (temp2['NCHS_urbanization'] == covidus.columns.levels[1][j])

    covidmask = temp2[mask]

    grouped = covidmask.groupby("county_name")["deaths"].sum()
    county = grouped.index
    deaths = grouped.values
    lines.x = county
    lines.y = deaths

    
heat_map.observe(on_selected, 'selected')


#--Dashboard----------------------------------------------------------------------------

fig =  bqplot.Figure(marks = [heat_map], axes = [c_ax, y_ax, x_ax])
fig_lines = bqplot.Figure(marks = [lines], axes = [x_axh, y_axh])

fig.layout.min_width='500px'
fig.layout.min_height='900px'
fig_lines.layout.min_width='500px'

myDashboard = ipywidgets.HBox([fig, fig_lines])
myDashboard

HBox(children=(Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='RdPu'), side='right'), …

#### Description for viewer

Left side of the dashboard lists the states and cities grouped according to the classification of the size and population density of the city, such as metropolitan, micropolitan, and the like. The color scale presents the confirmed covid-19 cases per 100000 people and the color scale is provided as well. Upon selecting one of the grids, right hand side graph will present the counties containing those type of cities and the deaths occurred from that county.

The relationship demonstrated by the visualization shows how as the cities grow larger there are more concentration of confirmed cases and, which counties containing certain cities were victim to the most damage due to lack of resources, the average age of the population, and the like. There certainly area lot more aspects to this visualization to be polished, however, such as labels. Just be aware that uncolored area(black area) do not contain data and may cause error upon selection.

#### Comment to grader

I tried leaving or commenting out as much cells as possible instead of deleting them, but since most of the work involved tweaking and testing out with different variables on the code I already had-from notes I've taken or past homeworks-it was difficult leaving out exactly the work I did.